### ISSUE TITLE
Raise something on storage abort

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-authoring#167]
We need to raise something when storage aborts.

I was just trying to save and save and save from webview with nothing actually saving, but from browser terminal my post and put requests were coming back as 200 Ok.

**Comment by edwoodward** [comment]
The issue is that we are not capturing errors when storage is not available in authoring. We should catch the error and return something besides a 200. This could be recreated by removing database connection or deleting content after it is created.
