### ISSUE TITLE
Search - Add the same content multiple times

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#180]
On demo, I added an already published Page to a Book.  I then tried to add the same Page again to the same Book and was able to.  Search should block content already in a Book from the search results.

**Comment by karenc** [comment]
@dak / @amberwebb I think the filtering for user search is done in webview (excluding users already added from the search result).  Could this also be done in webview?

**Comment by reedstrm** [comment]
This will have to be webview filtering, since the search happens on archive, which knows nothing about unpublished books. At minimum, it'd have to send all the page uuids as 'exclusions', so it might as well just post-process the results, instead.
