### ISSUE TITLE
403 when deleting Pages from Book

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#184]
I deleted a Book that contained Pages.  When I tried to delete the orphaned pages, I got a 403 Forbidden error
![screenshot from 2015-01-20 20 46 49](https://cloud.githubusercontent.com/assets/1394695/5830411/8826e7de-a0e5-11e4-8dd8-ff7736b363a7.png)

**Comment by karenc** [comment]
Could you also include the uuid of the book and the page please?

**Comment by edwoodward** [comment]
This might have been related to a code problem Ross fixed last night.  
I'll try to duplicate later today.

**Comment by edwoodward** [comment]
This is  working correctly now.
