### ISSUE TITLE
Logged in using Google 770 items in new Workspace

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#185]
Derek Ford Reported

When I go to My Workspace 770 items show up (on a new account), all of which have the Edited Date of "Invalid Date".

When I click the refresh button the 770 items disappear and I see "Empty Workspace. ..."

**Comment by karenc** [comment]
Unable to reproduce this bug, tested with a new google account.

**Comment by edwoodward** [comment]
I'll see if Derek can reproduce it this afternoon.

**Comment by edwoodward** [comment]
Closing since it cannot be reproduced.
