### ISSUE TITLE
Creating a new Page or Book logged in as Google fails

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#186]
When I try to create a Page or Book from the New dropdown I receive a popup which says "There was a problem saving. Please try again"

**Comment by edwoodward** [comment]
Derek Ford reported this

**Comment by karenc** [comment]
It works for me.  Is this still failing for Derek?

**Comment by edwoodward** [comment]
I'll get Derek to try and reproduce it this afternoon.

**Comment by pumazi** [comment]
This is working for me. And last I heard, it was working for others...
