### ISSUE TITLE
Roles - Twitter login does not receive roles notification

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#191]
Alana reported this

I added Alina Slavik & Helene McCarron as authors, but Helene never received notification. Helene used Twitter to login.

**Comment by amberwebb** [comment]
@edwoodward Did you add the username for Helene associated with her Twitter account? Maybe Helene has more than one login.

**Comment by edwoodward** [comment]
I'll check with her tomorrow about the login id.

**Comment by karenc** [comment]
I don't think email address is required for creating a openstax account.  Twitter doesn't give us any email addresses and the "create your account" form doesn't have an email field.  So I'm going to open an issue for accounts.
