### ISSUE TITLE
Cannot run individual unit tests

### ISSUE THREAD

**Issue by rich-hart** [Connexions/cnx-authoring#202]
Would be useful for debugging purposes if this functionality was available.

**Comment by pumazi** [comment]
Perhaps you are asking for something like: ``python setup.py test -s cnxauthoring.tests.test_utils.UtilsTests.test_declare_licensors``

**Comment by rich-hart** [comment]
Thanks!  Karen just pointed it out to me as well.  I've usually be able to get by with just using python -m unittest.  I didn't realize it made such a difference
