### ISSUE TITLE
Incorrect user login

### ISSUE THREAD

**Issue by amberwebb** [Connexions/cnx-authoring#206]
Connexions/webview#955

**Comment by pumazi** [comment]
Set all responses to return the HTTP header ``Cache-Control: no-cache``.

**Comment by pumazi** [comment]
BTW, The proper way to do this will be to subscribe to the ``NewResponse`` event. See also [the pyramid.events docs](http://docs.pylonsproject.org/projects/pyramid/en/1.3-branch/api/events.html).

**Comment by reedstrm** [comment]
Make tjhe Cache-Control: no-cache for any authenticated response, please.
