### ISSUE TITLE
Publishing - As an added author, the publish button won't work for me

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#216]
As an author added to the content by the content creator, the publish button is visible (blue) and allows me to fill in the publishing modal, but never publishes.
**Recreate**

    Create a page as 'billy'.
    Add 'grim' to the authors list.
    Sign out
    Sign in as 'grim'
    Accept the author role.
    Click the publish button on the page.

**Issue**

'grim' was never given permission to publish. So I'm not sure why, as 'grim', I have the ability to click the button.

I experienced this locally and have not tried to reproduce it on dev or beta.

See original issue at https://github.com/Connexions/webview/issues/982

**Comment by pumazi** [comment]
This just needs to add authors to the list of attributed roles we roll through in the ``declare_acl`` function. See https://github.com/Connexions/cnx-authoring/blob/9d0a575d4da5541a6e0e14529aa0f6b2a83e2b5a/cnxauthoring/utils.py#L387
